config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
  get '/home', to: 'static_pages#home'
  get '/tweet', to: 'static_pages#tweet'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :tweets, only: [:create] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :time_zone,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    # around_action :set_time_zone, if: :current_user  
    # private
    # def set_time_zone(&block)
    #   Time.use_zone(current_user.timezone)
    # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      Time.zone=user.timezone
      redirect_to user
      # Log the user in and redirect to the user's show page.
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
        @tweet = current_user.tweets.build if logged_in?
  end

  def tweet
  end

  def login
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  
  before_action :logged_in_user, only: [:create]
  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = "Tweet created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Successfullly Registered"
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation,:consumer_key,:consumer_secret,
                                   :access_token,:access_token_secret,:time_zone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Tweet Scheduler"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end
  

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def fill_time_zones
      @timezones=
                  "American Samoa
                  International Date Line West
                  Midway Island
                  Hawaii
                  Alaska
                  Pacific Time (US & Canada)
                  Tijuana
                  Arizona
                  Chihuahua
                  Mazatlan
                  Mountain Time (US & Canada)
                  Central America
                  Central Time (US & Canada)
                  Guadalajara
                  Mexico City
                  Monterrey
                  Saskatchewan
                  Bogota
                  Eastern Time (US & Canada)
                  Indiana (East)
                  Lima
                  Quito
                  Atlantic Time (Canada)
                  Caracas
                  Georgetown
                  La Paz
                  Santiago
                  Newfoundland
                  Brasilia
                  Buenos Aires
                  Greenland
                  Montevideo
                  Mid-Atlantic
                  Azores
                  Cape Verde Is.
                  Casablanca
                  Dublin
                  Edinburgh
                  Lisbon
                  London
                  Monrovia
                  UTC
                  Amsterdam
                  Belgrade
                  Berlin
                  Bern
                  Bratislava
                  Brussels
                  Budapest
                  Copenhagen
                  Ljubljana
                  Madrid
                  Paris
                  Prague
                  Rome
                  Sarajevo
                  Skopje
                  Stockholm
                  Vienna
                  Warsaw
                  West Central Africa
                  Zagreb
                  Zurich
                  Athens
                  Bucharest
                  Cairo
                  Harare
                  Helsinki
                  Istanbul
                  Jerusalem
                  Kaliningrad
                  Kyiv
                  Pretoria
                  Riga
                  Sofia
                  Tallinn
                  Vilnius
                  Baghdad
                  Kuwait
                  Minsk
                  Moscow
                  Nairobi
                  Riyadh
                  St. Petersburg
                  Volgograd
                  Tehran
                  Abu Dhabi
                  Baku
                  Muscat
                  Samara
                  Tbilisi
                  Yerevan
                  Kabul
                  Ekaterinburg
                  Islamabad
                  Karachi
                  Tashkent
                  Chennai
                  Kolkata
                  Mumbai
                  New Delhi
                  Sri Jayawardenepura
                  Kathmandu
                  Almaty
                  Astana
                  Dhaka
                  Urumqi
                  Rangoon
                  Bangkok
                  Hanoi
                  Jakarta
                  Krasnoyarsk
                  Novosibirsk
                  Beijing
                  Chongqing
                  Hong Kong
                  Irkutsk
                  Kuala Lumpur
                  Perth
                  Singapore
                  Taipei
                  Ulaanbaatar
                  Osaka
                  Sapporo
                  Seoul
                  Tokyo
                  Yakutsk
                  Adelaide
                  Darwin
                  Brisbane
                  Canberra
                  Guam
                  Hobart
                  Melbourne
                  Port Moresby
                  Sydney
                  Vladivostok
                  Magadan
                  New Caledonia
                  Solomon Is.
                  Srednekolymsk
                  Auckland
                  Fiji
                  Kamchatka
                  Marshall Is.
                  Wellington
                  Chatham Is."
                 @timezones=@timezones.split("\n").map{|i| i}
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <h3>System Time:<%=Time.now %> Application Time: <%=Time.current%></h3>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Tweet-R", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Tweets", tweet_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
        </li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to "Log in", login_path %></li>
  <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
    <h1>Tweet-R</h1>
    <p>
     <% if logged_in? %>
      <h3>Hello <%= current_user.name %></h3>
      <hr>
      <br>
      <%= form_for(@tweet) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="field">
          <%= f.text_area :content, placeholder: "Compose new Tweet..." %>
        </div>
        <%= f.submit "Post", class: "btn btn-primary" %>
      <% end %>
    </p>
    <% else %>
      <%= link_to "Sign up now!", signup_path, class: "btn-primary" %>
    <% end %>  
</html>

app/views/static_pages/register.html.erb
<% provide(:title, "Register") %>
<h1>Register</h1>
<p>
  New User Registers Here
</p>

app/views/static_pages/tweet.html.erb
<% provide(:title, "Tweet") %>
<h1>Tweet-R</h1>

<p>
    This is Where i tweet
    <select>
    <%= fill_time_zones.each{|i|%>
      <option value=<%= i %>><%= i %></option>
    <%}%>
    </select>  

</p>

app/views/static_pages/tweets.html.erb
<% provide(:title, "Tweet") %>
<h1>Tweet-R</h1>
<p>
    This is Where i tweet
</p>

app/views/tweets/_tweet.html.erb
<li id="tweet">
  <span class="user"><%= link_to user%></span>
  <span class="content"><%=%></span>
  </span>
</li>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>

      <%= render 'shared/error_messages',  object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :consumer_key , "Consumer Key " %>
      <%= f.text_field :consumer_key  %>

      <%= f.label :consumer_secret, "Consumer Secret" %>
      <%= f.text_field :consumer_secret %>

      <%= f.label :access_token, "Access Token" %>
      <%= f.text_field :access_token %>

      <%= f.label :access_token_secret, "Access Token Secret" %>
      <%= f.text_field :access_token_secret %>  

      <%= f.label :time_zone, "Select Time Zone" %>
      <%= f.select :time_zone, options_for_select(fill_time_zones.collect{ |u| [u,u] }),prompt: 'Select One'%>          

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
   
</div>